import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  // Laptops
  {
    _id: uuid(),
    category: "Laptop",
    name: "HP Spectre x360",
    specification: "15.6-inch, Intel i7, 16GB RAM, 512GB SSD",
    price: 12999,
    deliveryInDays: 5,
    url: "https://www.example.com/laptops/hp-spectre-x360",
    rating: 4,
  },
  {
    _id: uuid(),
    category: "Laptop",
    name: "Dell XPS 13",
    specification: "13.3-inch, Intel i5, 8GB RAM, 256GB SSD",
    price: 9999,
    deliveryInDays: 3,
    url: "https://www.example.com/laptops/dell-xps-13",
    rating: 4.5,
  },
  {
    _id: uuid(),
    category: "Laptop",
    name: "MacBook Pro",
    specification: "16-inch, Apple M1, 16GB RAM, 1TB SSD",
    price: 23999,
    deliveryInDays: 7,
    url: "https://www.example.com/laptops/macbook-pro",
    rating: 5,
  },
  {
    _id: uuid(),
    category: "Laptop",
    name: "Lenovo ThinkPad X1 Carbon",
    specification: "14-inch, Intel i7, 16GB RAM, 512GB SSD",
    price: 14999,
    deliveryInDays: 4,
    url: "https://www.example.com/laptops/lenovo-thinkpad-x1-carbon",
    rating: 4.5,
  },
  {
    _id: uuid(),
    category: "Laptop",
    name: "Asus ROG Zephyrus G14",
    specification: "14-inch, AMD Ryzen 9, 32GB RAM, 1TB SSD",
    price: 17999,
    deliveryInDays: 6,
    url: "https://www.example.com/laptops/asus-rog-zephyrus-g14",
    rating: 5,
  },
  {
    _id: uuid(),
    category: "Laptop",
    name: "Acer Swift 3",
    specification: "14-inch, Intel i5, 8GB RAM, 256GB SSD",
    price: 6999,
    deliveryInDays: 2,
    url: "https://www.example.com/laptops/acer-swift-3",
    rating: 3.5,
  },
  {
    _id: uuid(),
    category: "Laptop",
    name: "Dell Inspiron 15",
    specification: "15.6-inch, AMD Ryzen 7, 16GB RAM, 1TB SSD",
    price: 5000,
    deliveryInDays: 4,
    url: "https://www.example.com/laptops/dell-inspiron-15",
    rating: 2.5,
  },
  {
    _id: uuid(),
    category: "Laptop",
    name: "Microsoft Surface Laptop 4",
    specification: "13.5-inch, Intel i7, 16GB RAM, 512GB SSD",
    price: 11999,
    deliveryInDays: 3,
    url: "https://www.example.com/laptops/microsoft-surface-laptop-4",
    rating: 4.5,
  },
  {
    _id: uuid(),
    category: "Laptop",
    name: "Razer Blade 15",
    specification: "15.6-inch, Intel i9, 32GB RAM, 1TB SSD",
    price: 18999,
    deliveryInDays: 6,
    url: "https://www.example.com/laptops/razer-blade-15",
    rating: 4.75,
  },
  {
    _id: uuid(),
    category: "Laptop",
    name: "LG Gram 17",
    specification: "17-inch, Intel i7, 16GB RAM, 1TB SSD",
    price: 15999,
    deliveryInDays: 5,
    url: "https://www.example.com/laptops/lg-gram-17",
    rating: 3.75,
  },
  // Phones
  {
    _id: uuid(),
    category: "Phone",
    name: "iPhone 13 Pro",
    specification: "6.1-inch Super Retina XDR, Apple A15 Bionic, 128GB",
    price: 1099,
    deliveryInDays: 3,
    url: "https://www.example.com/phones/iphone-13-pro",
    rating: 5,
  },
  {
    _id: uuid(),
    category: "Phone",
    name: "Samsung Galaxy S21",
    specification: "6.2-inch Dynamic AMOLED, Snapdragon 888, 256GB",
    price: 899,
    deliveryInDays: 4,
    url: "https://www.example.com/phones/samsung-galaxy-s21",
    rating: 5,
  },
  {
    _id: uuid(),
    category: "Phone",
    name: "Google Pixel 6",
    specification: "6.4-inch OLED, Google Tensor, 128GB",
    price: 799,
    deliveryInDays: 5,
    url: "https://www.example.com/phones/google-pixel-6",
    rating: 3.75,
  },
  {
    _id: uuid(),
    category: "Phone",
    name: "OnePlus 9 Pro",
    specification: "6.7-inch Fluid AMOLED, Snapdragon 888, 256GB",
    price: 999,
    deliveryInDays: 3,
    url: "https://www.example.com/phones/oneplus-9-pro",
    rating: 3.75,
  },
  {
    _id: uuid(),
    category: "Phone",
    name: "Xiaomi Mi 11",
    specification: "6.81-inch AMOLED, Snapdragon 888, 128GB",
    price: 799,
    deliveryInDays: 4,
    url: "https://www.example.com/phones/xiaomi-mi-11",
    rating: 3,
  },
  {
    _id: uuid(),
    category: "Phone",
    name: "Sony Xperia 1 III",
    specification: "6.5-inch OLED, Snapdragon 888, 256GB",
    price: 1299,
    deliveryInDays: 5,
    url: "https://www.example.com/phones/sony-xperia-1-iii",
    rating: 3.75,
  },
  {
    _id: uuid(),
    category: "Phone",
    name: "LG Velvet",
    specification: "6.8-inch OLED, Snapdragon 765, 128GB",
    price: 599,
    deliveryInDays: 3,
    url: "https://www.example.com/phones/lg-velvet",
    rating: 3.75,
  },
  {
    _id: uuid(),
    category: "Phone",
    name: "Motorola Edge+",
    specification: "6.7-inch OLED, Snapdragon 865, 256GB",
    price: 899,
    deliveryInDays: 4,
    url: "https://www.example.com/phones/motorola-edge-plus",
    rating: 4.75,
  },
  {
    _id: uuid(),
    category: "Phone",
    name: "Nokia 8.3",
    specification: "6.81-inch IPS LCD, Snapdragon 765G, 128GB",
    price: 499,
    deliveryInDays: 5,
    url: "https://www.example.com/phones/nokia-8-3",
    rating: 3.5,
  },
  {
    _id: uuid(),
    category: "Phone",
    name: "Realme GT",
    specification: "6.43-inch Super AMOLED, Snapdragon 888, 128GB",
    price: 499,
    deliveryInDays: 3,
    url: "https://www.example.com/phones/realme-gt",
    rating: 4,
  },
  // Headphones
  {
    _id: uuid(),
    category: "Headphones",
    name: "Sony WH-1000XM4",
    specification: "Wireless Over-Ear Headphones",
    price: 349,
    deliveryInDays: 2,
    url: "https://www.example.com/headphones/sony-wh-1000xm4",
    rating: 5,
  },
  {
    _id: uuid(),
    category: "Headphones",
    name: "Bose QuietComfort 35 II",
    specification: "Wireless Over-Ear Headphones",
    price: 299,
    deliveryInDays: 3,
    url: "https://www.example.com/headphones/bose-quietcomfort-35-ii",
    rating: 4.5,
  },
  {
    _id: uuid(),
    category: "Headphones",
    name: "Sennheiser HD 660 S",
    specification: "Open-Back Over-Ear Headphones",
    price: 499,
    deliveryInDays: 4,
    url: "https://www.example.com/headphones/sennheiser-hd-660-s",
    rating: 5,
  },
  {
    _id: uuid(),
    category: "Headphones",
    name: "Jabra Elite 85t",
    specification: "Wireless Earbuds",
    price: 229,
    deliveryInDays: 2,
    url: "https://www.example.com/headphones/jabra-elite-85t",
    rating: 4.5,
  },
  {
    _id: uuid(),
    category: "Headphones",
    name: "Apple AirPods Pro",
    specification: "Wireless Earbuds",
    price: 249,
    deliveryInDays: 3,
    url: "https://www.example.com/headphones/apple-airpods-pro",
    rating: 4,
  },
  {
    _id: uuid(),
    category: "Headphones",
    name: "Beats Solo Pro",
    specification: "Wireless On-Ear Headphones",
    price: 199,
    deliveryInDays: 4,
    url: "https://www.example.com/headphones/beats-solo-pro",
    rating: 3.5,
  },
  {
    _id: uuid(),
    category: "Headphones",
    name: "Bose SoundSport Free",
    specification: "True Wireless Earbuds",
    price: 179,
    deliveryInDays: 2,
    url: "https://www.example.com/headphones/bose-soundsport-free",
    rating: 4.5,
  },
  {
    _id: uuid(),
    category: "Headphones",
    name: "JBL Quantum 800",
    specification: "Wireless Gaming Headset",
    price: 149,
    deliveryInDays: 3,
    url: "https://www.example.com/headphones/jbl-quantum-800",
    rating: 3,
  },
  {
    _id: uuid(),
    category: "Headphones",
    name: "SteelSeries Arctis 7",
    specification: "Wireless Gaming Headset",
    price: 149,
    deliveryInDays: 4,
    url: "https://www.example.com/headphones/steelseries-arctis-7",
    rating: 3,
  },
  {
    _id: uuid(),
    category: "Headphones",
    name: "Anker Soundcore Liberty Air 2 Pro",
    specification: "Wireless Earbuds",
  price: 99.99,
    deliveryInDays: 2,
    url: "https://www.example.com/headphones/anker-soundcore-liberty-air-2-pro",
    rating: 2.5,
  },
  // ... (additional laptops, phones, and headphones)
];
